name: ci

on:
  pull_request:

jobs:
  lint-bash-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Lint Bash scripts
        uses: docker://koalaman/shellcheck-alpine:v0.7.0
        with:
          args: .github/lint-scripts.sh

  lint-docker-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3    
      - name: lint zammad dockerfile
        uses: brpaz/hadolint-action@master
        with:
          dockerfile: Dockerfile

  build-and-run-docker:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    needs: 
      - lint-bash-scripts
      - lint-docker-file
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: build docker container
        run: docker build --pull --no-cache --build-arg BUILD_DATE="$(date -u +'%Y-%m-%dT%H:%M:%SZ')" -t zammad .
      - name: docker run
        run: docker run -d -p 80:80 --name zammad-test --rm zammad
      - name: add autowizard file
        run: docker cp .github/auto_wizard.json zammad-test:/opt/zammad
      - name: run tests
        run: .github/tests.sh

  run-remote-docker-image:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    needs:
      - lint-bash-scripts
      - lint-docker-file
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: docker pull image
        run: docker pull zammad/zammad:latest
      - name: docker run
        run: docker run -d -p 80:80 --name zammad-test --rm zammad/zammad:latest
      - name: add autowizard file
        run: docker cp .github/auto_wizard.json zammad-test:/opt/zammad
      - name: run tests
        run: .github/tests.sh
